transacciones = [
    {"pan", "leche", "huevos", "café", "azúcar", "mantequilla"},
    {"cereal", "leche", "plátano", "yogurt", "miel"},
    {"arroz", "frijoles", "aceite", "sal", "pollo"},
    {"pan", "queso", "jamón", "mantequilla", "jugo"},
    {"fideos", "salsa de tomate", "queso", "pan"},
    {"café", "leche", "galletas", "azúcar"},
    {"huevos", "tocino", "pan", "jugo", "mantequilla"},
    {"yogurt", "manzanas", "granola", "miel"},
    {"arroz", "pollo", "aceite", "sal"},
    {"cereal", "leche", "pan"},
    {"galletas", "chocolate", "refresco"},
    {"queso", "jamón", "pan", "mantequilla"},
    {"fideos", "salsa de tomate", "queso"},
    {"pan", "leche", "mantequilla", "café"},
    {"cereal", "leche", "jugo", "yogurt"},
    {"arroz", "frijoles", "pollo", "sal"},
    {"refresco", "papas fritas", "galletas"},
    {"jamón", "queso", "pan", "huevos"},
    {"huevos", "leche", "tocino", "pan"},
    {"yogurt", "granola", "miel"},
    {"jugo", "pan", "mantequilla", "queso"},
    {"cereal", "leche", "azúcar", "plátano"},
    {"galletas", "chocolate", "refresco"},
    {"queso", "jamón", "pan"},
    {"arroz", "pollo", "sal"},
    {"fideos", "salsa de tomate", "queso"},
    {"pan", "huevos", "café", "azúcar"},
    {"yogurt", "manzanas", "miel"},
    {"cereal", "leche", "plátano"},
    {"pan", "queso", "jamón", "tomate"},
    {"galletas", "chocolate", "refresco"},
    {"arroz", "frijoles", "pollo", "sal"},
    {"fideos", "salsa de tomate", "queso"},
    {"pan", "leche", "huevos", "café"},
    {"cereal", "leche", "yogurt"},
    {"huevos", "tocino", "pan", "jugo"},
    {"yogurt", "granola", "miel"},
    {"arroz", "pollo", "sal"},
    {"cereal", "leche", "jugo"},
    {"galletas", "chocolate", "refresco"},
    {"queso", "jamón", "pan"},
    {"fideos", "salsa de tomate", "queso"},
    {"pan", "leche", "mantequilla", "galletas"},
    {"cereal", "leche", "plátano", "miel"},
    {"arroz", "frijoles", "pollo"},
    {"galletas", "chocolate", "jugo"},
    {"queso", "jamón", "pan"},
    {"huevos", "tocino", "pan"},
    {"yogurt", "granola", "miel"},
    {"fideos", "salsa de tomate", "queso"},
    {"arroz", "pollo", "aceite", "sal"},
    {"jugo", "pan", "mantequilla"},
    {"cereal", "leche", "yogurt"},
    {"galletas", "chocolate", "refresco"},
    {"queso", "jamón", "pan"},
    {"fideos", "salsa de tomate", "queso"},
    {"pan", "huevos", "mantequilla"},
    {"arroz", "frijoles", "pollo"},
    {"cereal", "leche", "yogurt"},
    {"galletas", "chocolate", "refresco"},
    {"queso", "jamón", "pan"},
    {"fideos", "salsa de tomate", "queso"},
    {"café", "leche", "azúcar"},
    {"jugo", "galletas"},
    {"pan", "leche", "huevos"},
    {"arroz", "pollo"},
    {"cereal", "leche"},
    {"huevos", "pan"},
    {"galletas", "jugo"},
    {"jamón", "queso", "pan"},
    {"leche", "galletas"},
    {"yogurt", "manzanas"},
    {"pan", "queso"},
    {"huevos", "tocino"},
    {"arroz", "frijoles"},
    {"pan", "mantequilla", "miel"},
    {"refresco", "papas fritas"},
    {"cereal", "leche"},
    {"arroz", "pollo"},
    {"jugo", "manzanas"},
    {"jamón", "queso"},
    {"café", "leche"},
    {"manzanas", "jugo"},
    {"pan", "galletas"},
    {"huevos", "leche"},
    {"galletas", "chocolate"},
    {"pan", "mantequilla"},
    {"queso", "jamón"},
    {"cereal", "leche"},
]